using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable
// Autogenerated by Visual Studio
// Creates the tables using the Module model class
namespace ScheduleBlenderWebApp.Migrations
{
    /// <inheritdoc />
    public partial class SecondMigration : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Modules",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CurrentSemester = table.Column<string>(type: "nvarchar(15)", nullable: false),
                    WeeksInSemester = table.Column<int>(type: "int", nullable: false),
                    StartDate = table.Column<string>(type: "nvarchar(12)", nullable: false),
                    Code = table.Column<string>(type: "nvarchar(12)", nullable: false),
                    Name = table.Column<string>(type: "nvarchar(120)", nullable: false),
                    Credits = table.Column<int>(type: "int", nullable: false),
                    WeeklyClassHours = table.Column<int>(type: "int", nullable: false),
                    WeeklySelfStudyHours = table.Column<int>(type: "int", nullable: true),
                    WeeklySelfStudyHoursCompleted = table.Column<int>(type: "int", nullable: true),
                    RemainingWeeklySelfStudyHours = table.Column<int>(type: "int", nullable: true),
                    SelfStudyDateCompleted = table.Column<string>(type: "nvarchar(12)", nullable: true),
                    UserId = table.Column<string>(type: "nvarchar(450)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Modules", x => x.Id);
                });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Modules");
        }
    }
}
