using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;

namespace ScheduleBlenderWebApp.Areas.Identity.Data;

// Autogenerated by Visual Studio
// Add profile data for application users by adding properties to the User class
public class ApplicationUser : IdentityUser
{
    // Adds the DisplayName field to the database 
    [PersonalData]
    [Column(TypeName = "nvarchar(100)")]
    public required string Displayname { get; set; }
}

