using DataCalculationLibrary2.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using ScheduleBlenderWebApp.Areas.Identity.Data;

namespace Auth.Data;

// Autogenerated by Visual Studio
public class ScheduleBlenderWebAppContext : IdentityDbContext<ApplicationUser>
{
    public ScheduleBlenderWebAppContext(DbContextOptions<ScheduleBlenderWebAppContext> options)
        : base(options)
    {
    }

    protected override void OnModelCreating(ModelBuilder builder)
    {
        base.OnModelCreating(builder);
        // Customize the ASP.NET Identity model and override the defaults if needed.
        // For example, you can rename the ASP.NET Identity table names and more.
        // Add your customizations after calling base.OnModelCreating(builder);
    }

    public DbSet<Module> Modules { get; set; }
}
